name: CI

on: [push, pull_request]

env:
  UPSTASH_REDIS_REST_URL: https://redis.com
  UPSTASH_REDIS_REST_TOKEN: token

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Typecheck
        run: yarn typecheck

      - name: Lint
        run: yarn lint
